ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "dcsi"
  site-url: "https://simon-lawyer.github.io/dcsi"
  description: "A helper app for Data, Code, and Social Innovation taught at Lincoln Alexander Law School"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/simon-lawyer/dcsi"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/simon-lawyer/dcsi"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
