# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/dcsi',
                'doc_host': 'https://simon-lawyer.github.io',
                'git_url': 'https://github.com/simon-lawyer/dcsi',
                'lib_path': 'dcsi'},
  'syms': {'dcsi.core': {'dcsi.core.foo': ('core.html#foo', 'dcsi/core.py')}}}