# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_helper.ipynb.

# %% auto 0
__all__ = ['url', 'Helper']

# %% ../00_helper.ipynb 3
url = 'https://refugeelab.ca/wp-content/uploads/2020/08/2019_-RPD_-Data.xlsx'

# %% ../00_helper.ipynb 4
class Helper:
    "This class contains some information that will help us"
    def __init__(self): 
        self.url = 'https://refugeelab.ca/wp-content/uploads/2020/08/2019_-RPD_-Data.xlsx' # Identifies a useful URL
    def __str__(self) : return f'Nice job! You loaded the class application. In the next cell, call the "name" function. Hint: XXX.name()'
    __repr__ = __str__
    def name(self):
        person_name = input('Enter your name: ')
        print(f'\nHi {person_name}, you are doing great!')
        print(f'The purpose of this library is to give you easy access to information when you need it.')
        print(f'Type in XXX.url into the next cell')
